name: connectivity_checker
description: A new Flutter package which provides network-aware widgets.It allows Flutter apps provide feedback on your app when it's not connected to it, or when there's no connection.
version: 1.0.0
documentation: https://github.com/govindmaheshwari2/connectivity_checker
homepage: https://github.com/govindmaheshwari2/connectivity_checker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1 #run to sort import => flutter pub run import_sorter:main

flutter:
